name: Run Pytest on Main Branch

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'  # Replace with your required Python version

      - name: Install dependencies
        working-directory: ./PartA
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Ensure your dependencies are listed in this file

      - name: Run Pytest
        working-directory: ./PartA
        run: |
          pytest
